import { library } from "@fortawesome/fontawesome-svg-core";

import {
  faBars,
  faXmark,
  faAngleUp,
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faArrowLeft,
  faArrowRight,
  faArrowDown,
  faArrowUp,
  faArrowRightFromBracket,
  faQuestion,
  faGear,
  faSliders,
  faUserTie,
  faPalette,
  faChartColumn,
  faUserGroup,
  faFolder,
  faFileLines,
  faNewspaper,
  faImages,
  faCalendar,
  faListCheck,
  faMagnifyingGlass,
  faSuitcase,
  faArrowTrendUp,
  faArrowUpFromBracket,
  faImage,
  faDownload,
  faCheck,
  faCopy,
  faShieldHalved,
  faChartLine,
  faCircleExclamation,
} from "@fortawesome/free-solid-svg-icons";

import {
  faBell,
  faUser,
  faEye,
  faEyeSlash,
  faPenToSquare,
  faTrashCan,
} from "@fortawesome/free-regular-svg-icons";

import {} from "@fortawesome/free-brands-svg-icons";

library.add(
  faBars,
  faXmark,
  faAngleUp,
  faAngleDown,
  faAngleLeft,
  faAngleRight,
  faArrowLeft,
  faArrowRight,
  faArrowDown,
  faArrowUp,
  faArrowRightFromBracket,
  faQuestion,
  faGear,
  faSliders,
  faUserTie,
  faListCheck,
  faFolder,
  faFileLines,
  faNewspaper,
  faImages,
  faCalendar,
  faPalette,
  faChartColumn,
  faUserGroup,
  faMagnifyingGlass,
  faBell,
  faUser,
  faSuitcase,
  faEye,
  faArrowTrendUp,
  faPenToSquare,
  faEyeSlash,
  faArrowUpFromBracket,
  faTrashCan,
  faImage,
  faFileLines,
  faDownload,
  faCopy,
  faCheck,
  faShieldHalved,
  faChartLine,
  faCircleExclamation,
);
