import { library } from "@fortawesome/fontawesome-svg-core";

import {
  faBars,
  faXmark,
  faQuestion,
  faGear,
  faSliders,
  faUserGroup,
  faUserPlus,
  faFileLines,
  faListCheck,
  faMagnifyingGlass,
  faSuitcase,
  faImage,
  faDownload,
  faCheck,
  faCopy,
  faShieldHalved,
  faChartLine,
  faCircleExclamation,
  faTv,
  faUserShield,
  faClipboardList,
  faArrowRightFromBracket,
  faTriangleExclamation,
  faBan,
  faFilter,
  faSort,
} from "@fortawesome/free-solid-svg-icons";

import {
  faBell,
  faUser,
  faEye,
  faEyeSlash,
  faPenToSquare,
  faTrashCan,
  faClock,
} from "@fortawesome/free-regular-svg-icons";

import {} from "@fortawesome/free-brands-svg-icons";

library.add(
  faBars,
  faXmark,
  faQuestion,
  faGear,
  faSliders,
  faListCheck,
  faFileLines,
  faUserGroup,
  faUserPlus,
  faMagnifyingGlass,
  faBell,
  faUser,
  faSuitcase,
  faEye,
  faPenToSquare,
  faEyeSlash,
  faTrashCan,
  faImage,
  faFileLines,
  faDownload,
  faCopy,
  faCheck,
  faShieldHalved,
  faChartLine,
  faCircleExclamation,
  faTv,
  faUserShield,
  faClipboardList,
  faArrowRightFromBracket,
  faClock,
  faTriangleExclamation,
  faBan,
  faFilter,
  faSort,
);
